apply theme to TextEditingUi + editable clipboard content radius
fcitx5-android/fcitx5-android pull request #489
Opened 2024-04-28 08:07 UTC by ccyybn

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/6e561439-8d17-4afe-8842-241739fede42)
![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/e04e1c1f-f811-43dd-9283-ae9a57da6e52)

2024-04-28 11:53 UTC, mokapsing commented
app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt 64行，radius未传值，93行同理

2024-04-28 11:53 UTC, mokapsing reviewed
app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt 64行，radius未传值，93行同理

2024-04-28 11:53 UTC, MokOopsing commented on app/src/main/java/org/fcitx/fcitx5/android/input/popup/PopupComponent.kt
> +    private val popupTextEditingRadius by lazy {
define but not used?

2024-04-28 12:44 UTC, ccyybn commented on app/src/main/java/org/fcitx/fcitx5/android/input/popup/PopupComponent.kt
> +    private val popupTextEditingRadius by lazy {
我还以为这是显示配置项的，已经删了

2024-04-28 12:45 UTC, ccyybn commented
> app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt 64行，radius未传值，93行同理

加了

2024-04-28 21:06 UTC, ccyybn commented
参考的 Gboard 的禁用按键逻辑

https://github.com/fcitx5-android/fcitx5-android/assets/7237501/aa06974f-b056-48e3-870f-9658785091e9

2024-04-29 00:38 UTC, mokapsing commented
> 禁用按键逻辑 与 Gboard 一致
> 
>  show.mp4

希望不要影响类似termux这种应用中的表现，例如上下切换history等

2024-04-29 02:39 UTC, rocka commented
这个 Select 键还有些问题，原本的实现是，只有在编辑器中有选择的文字时，才会变成蓝色（accentKeyBackgroundColor），取消选择后，就会变回普通按键的颜色

2024-04-29 03:09 UTC, rocka requested changes

2024-04-29 03:09 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt
> +        val radius: Int,
我觉得在 KeyDef 中引入 radius 的具体数值不太合适， KeyDef 中各字段的值大都表示某种“类别”，在 KeyView 实例化的时候才解释为具体的值。具体到这里，可能给 KeyView 加一个 `open fun  onSetRadius()` 会比较好。

2024-04-29 03:09 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            radius = ThemeManager.prefs.keyRadiusTextEditing.getValue()
这里每创建一个按钮都要调用一次 `getValue()` ，还是缓存一下会比较好

2024-04-29 03:09 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            radius = ThemeManager.prefs.keyRadiusTextEditing.getValue()
同上，需要缓存一下

2024-04-29 04:01 UTC, rocka commented on app/src/main/res/values-zh-rCN/strings.xml
> +    <string name="key_radius_clipboard">剪贴板内容圆角半径</string>
翻译在 transifex 上统一管理 https://www.transifex.com/fcitx/fcitx5-android/ 不要手动修改英文字符串的翻译，否则同步的时候会被覆盖掉

2024-04-29 04:01 UTC, rocka commented on app/src/main/res/values-zh-rTW/strings.xml
> +    <string name="key_radius_clipboard">剪貼簿內容圓角半徑</string>
同上

2024-04-29 04:05 UTC, rocka requested changes

2024-04-29 04:05 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            backspaceButton.isEnabled = true
按键禁用启用这些先不要改了，首先是会影响类似 termux 之类的无法提供 surrounding text 的应用的光标移动功能；其次因为 https://github.com/fcitx5-android/fcitx5-android/issues/472 ，光标移动的实现还需要大幅重构

2024-04-29 06:54 UTC, ccyybn commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            backspaceButton.isEnabled = true
在termux里面，Gboard直接禁用了整个文本编辑和其他附加功能，只有一个键盘，是不是这样就不会影响了

2024-04-29 08:42 UTC, ccyybn commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt
> +        val radius: Int,
我看KeyView里面 `val radius: Float` 是个不可变量，而且很多工作都是初始化的时候就完成了，如果后面再去改这个radius和 `appearanceView.background` 里面的 cornerRadius是不是不太方便改，也不太好

2024-04-29 08:49 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            backspaceButton.isEnabled = true
那当然不行了 ... 它们这种实现太偷懒了

2024-04-29 09:55 UTC, ccyybn commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt
> +            backspaceButton.isEnabled = true
我还是很喜欢这个按键禁用效果，那我留着自用吧，这里就删掉

2024-04-29 10:34 UTC, ccyybn commented
> 这个 Select 键还有些问题，原本的实现是，只有在编辑器中有选择的文字时，才会变成蓝色（accentKeyBackgroundColor），取消选择后，就会变回普通按键的颜色

这个改好了

2024-05-02 16:25 UTC, rocka commented
没开启按键边框的时候，原来按钮之间的分割线都没了：

<img src="https://github.com/fcitx5-android/fcitx5-android/assets/13914967/8ad697d4-f486-4c3b-8f6d-61c09dda7590" width="360">

另外，这里的按钮边距应该需要统一一下，感觉没必要跟随按键横向/纵向边距的设置，或者这个界面就不该复用 KeyView ...

<img src="https://github.com/fcitx5-android/fcitx5-android/assets/13914967/5dba4be5-f4d7-48ed-8e58-5ba26b7ef5c3" width="360">

而且感觉按钮的字体没必要用粗体 ...

2024-05-02 17:30 UTC, ccyybn commented
> 没开启按键边框的时候，原来按钮之间的分割线都没了：
> 
> <img alt="" width="360" src="https://private-user-images.githubusercontent.com/13914967/327504705-8ad697d4-f486-4c3b-8f6d-61c09dda7590.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjkxMTIsIm5iZiI6MTcxNDY2ODgxMiwicGF0aCI6Ii8xMzkxNDk2Ny8zMjc1MDQ3MDUtOGFkNjk3ZDQtZjQ4Ni00YzNiLThmNmQtNjFjMDlkZGE3NTkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE2NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZmFkN2Y2NGFhN2E0ZGUzYjdkODQyNWYwNTRhMDlkYzQ1NThmYTM5MTk2MWQxNTc4NmFmNDZhOWVmN2E4ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.49eQ8kbyvrTa8dKkWpUFQdqiUZZRezyYxISOvUUtbuk">
> 另外，这里的按钮边距应该需要统一一下，感觉没必要跟随按键横向/纵向边距的设置，或者这个界面就不该复用 KeyView ...
> 
> <img alt="" width="360" src="https://private-user-images.githubusercontent.com/13914967/327504084-5dba4be5-f4d7-48ed-8e58-5ba26b7ef5c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ2NjkxMTIsIm5iZiI6MTcxNDY2ODgxMiwicGF0aCI6Ii8xMzkxNDk2Ny8zMjc1MDQwODQtNWRiYTRiZTUtZjRkNy00OGVkLThlNTgtNWJhMjZiN2VmNWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAyVDE2NTMzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5Y2JiNzBkMDgxOWUyMWUzYjE3MjU0ZmM3YWRmNDRkM2MwMDBiZjkyNjM2NjVmYjMxNDk5M2U5MWNmODcwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2pTdB9TXwPFJBHEfm_pz7plIMmuN_iCHCTdimvAQZFQ">
> 而且感觉按钮的字体没必要用粗体 ...

审美差异吧，我觉得粗体好看一点，好像主键盘的符号切换键也是粗体，那个按钮还更小一点

没分割线是因为风格与主题统一，可能接受的人会多一些吧

纵向边距我主键盘也调小了的，看起来没那没维和，不过确实单独调整更好，横纵一样宽，这个我会加个选项控制

不复用KeyView改动有点大，如果要这样改并同时满足之前分割线的效果，我觉得很难达到代码要求，可能你来提交要方便一些

2024-05-03 19:17 UTC, ccyybn commented
@rocka 现在我加了选项，3种按钮随便选，每个人应该都满意了，你可以试试

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/129b880b-6fa1-4e5f-aed9-47d411169a09)


![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/0432a1ed-ae6f-4512-bfbb-eeb8b9a9b8b9)

2024-05-04 09:27 UTC, ccyybn commented
@rocka 

我下载 Release版 0.0.9 确认了下，之前线条效果的文本编辑按键有个bug，就是在我的平板上，这些线条是不可见的

![image](https://github.com/fcitx5-android/fcitx5-android/assets/7237501/3f2a1622-ec49-4d8a-b8cd-b117ce033e44)

2024-07-05 17:40 UTC, rocka commented
首先我得先道个歉，最近确实比较忙，没时间处理 PR ，尤其是这种规模比较大的 ... 然后就要开始挑刺儿了。

---

虽然之前提交的代码“看起来”达成了描述中的效果，但落到实现细节上，有些地方对已有封装类的使用有误，破坏了整体的抽象层次。比如，在 `TextEditingUi`

https://github.com/fcitx5-android/fcitx5-android/blob/ecfc97e3a5f6a5dbbdeda43ca5a0d76cad680c25/app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingUi.kt#L53-L60

和 `KeyDef`

https://github.com/fcitx5-android/fcitx5-android/blob/ecfc97e3a5f6a5dbbdeda43ca5a0d76cad680c25/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyDef.kt#L19-L36

中使用 [`ManagedPreference`](https://github.com/fcitx5-android/fcitx5-android/blob/ea2d5c8a439a4bc400ae976c5ded278f39c5ce12/app/src/main/java/org/fcitx/fcitx5/android/data/prefs/ManagedPreference.kt#L13) 。 `ManagedPreference` 是对 [SharedPreferences](https://developer.android.com/reference/android/content/SharedPreferences) 的封装，为其供类型以及选项值改变的监听，只应该在定义应用设置项时，比如 [`AppPrefs`](https://github.com/fcitx5-android/fcitx5-android/blob/master/app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt) 和 [`ThemePrefs`](https://github.com/fcitx5-android/fcitx5-android/blob/master/app/src/main/java/org/fcitx/fcitx5/android/data/theme/ThemePrefs.kt) 中使用，不应该被下放到 UI 的实现中。而 `KeyDef` 承担了定义键盘布局中按键外观与功能的责任，如非必要，不应该在其中定义 UI 中使用的具体数字（比如圆角半径的 px 或 dp 值），更不应该出现 Android 中的类对象（比如 `SharedPreferences`）。

其次，对 [Splitties View DSL](https://splitties.louiscad.com/modules/views-dsl/) 中 [`Ui`](https://github.com/LouisCAD/Splitties/blob/v3.0.0/modules/views-dsl/README.md#the-interface-for-user-interfaces-named-ui) 接口实现，或者更笼统地说，可复用的 UI 组件的实现，应该只关心在界面上显示的内容，不应该与其它业务逻辑耦合。例如 `PickerPageUi`

https://github.com/fcitx5-android/fcitx5-android/blob/ecfc97e3a5f6a5dbbdeda43ca5a0d76cad680c25/app/src/main/java/org/fcitx/fcitx5/android/input/picker/PickerPageUi.kt#L48-L56

中就不应该将 `recentlyUsedFileName` 作为构造函数的参数传入。如果你想根据 `recentlyUsedFileName` 的值来控制边框，在外层传入一个 `Boolean` 类型足矣。

另外，没必要每种实现都加个选项，让符号键盘和文本编辑界面都跟随键盘的按键边框设置就够了，也没必要每个边距都独立成一个设置，否则设置界面的膨胀速度就不可控了。

最后，每个 PR 应该只包含一个功能的实现，不应该把多个互不相关的功能放在一起，否则会给 review 增加不必要的工作量（要额外区分哪些文件实现了哪些功能），也不方便合并的时候直接 squash 。

---

代码我已经全都重构成比较符合目前编码风格的实现了，如果有问题可以再商量，没问题的话就按照现在的实现合并了（可能还需要再 rebase 一下，把相关的功能 squash 成一个 commit）。

2024-07-05 17:56 UTC, ccyybn commented
@rocka 一切按照你改的来，这代码我改起来头疼，最近也比较忙

2024-07-05 19:11 UTC, rocka approved these changes

2024-07-05 19:11 UTC, merged