`KeyAction` for dealing with left & right cursor moving
fcitx5-android/fcitx5-android pull request #550
Opened 2024-07-30 11:37 UTC by LatticeLadder

对空格键左右滑动以及`TextEditingUi`中的左右移动的逻辑进行了修改，按照`getExtractedText()`来判断应用支持报告光标位置与否，若像Termux这种不支持的就直接发送按键，否则会判断文字边界。这样应该能解决网易云音乐、WebView之类移动光标会超出输入框范围的问题。

2024-07-30 14:31 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CommonKeyActionListener.kt
> +                    }
Calling [`InputConnection#getExtractedText`](https://developer.android.com/reference/android/view/inputmethod/InputConnection#getExtractedText(android.view.inputmethod.ExtractedTextRequest,%20int)) every time when a `MoveCursorAction` comes is probably not a good idea, since it requires an  IPC round-trip for those infomation.

2024-07-30 14:42 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CommonKeyActionListener.kt
> +                    cursorMovingOccupied = false
Can you explain why it needs to block the thread? While it's already blocking, what's the propese of `cursorMovingOccupied`?

2024-07-30 14:42 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyAction.kt
> +
It's better to declare the enum inside `MoveCursorAction` to keep the code clean.

```suggestion
    data class MoveCursorAction(val direction: Direction) : KeyAction() {
        enum class Direction { Left, Right }
    }

```

2024-07-31 13:17 UTC, LatticeLadder commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CommonKeyActionListener.kt
> +                    cursorMovingOccupied = false
抱歉，一直以为每个`KeyAction`是异步的，后面试验了发现不是。现在的实现又改了

2024-07-31 13:18 UTC, LatticeLadder commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyAction.kt
> +
现在复用了，不好折叠，要不你`typealias`吧

2024-08-11 14:11 UTC, rocka requested changes
IMO it's better to reuse `MoveSelectionAction` rather than creating more `KeyAction` classes:

https://github.com/fcitx5-android/fcitx5-android/blob/8b4299ed8520c0856c84bd8b6015a6686806ac3f/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt#L187-L202

https://github.com/fcitx5-android/fcitx5-android/blob/8b4299ed8520c0856c84bd8b6015a6686806ac3f/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CommonKeyActionListener.kt#L135-L153

I would also like to avoid calling `InputConnection#getExtractedText` just for getting selection position, since `currentInputSelection` in `FcitxInputMethodService` has already been tracking it:

https://github.com/fcitx5-android/fcitx5-android/blob/8b4299ed8520c0856c84bd8b6015a6686806ac3f/app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt#L88-L91

https://github.com/fcitx5-android/fcitx5-android/blob/8b4299ed8520c0856c84bd8b6015a6686806ac3f/app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt#L586-L599

As for checking whether `currentInputConnection` supports `setSelection`, I suggest checking [`currentEditorInfo.inputType`](https://developer.android.com/reference/android/view/inputmethod/EditorInfo#inputType) against [`InputType.TYPE_NULL`](https://developer.android.com/reference/android/text/InputType#TYPE_NULL), and assume all other types would support `setSelection`.

2024-08-11 14:11 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +                                    onAction(KeyAction.MoveCursorAction(direction))
Since `TrackCursorAction` and `MoveCursorAction` are always sent in sequence, why separate them into different `KeyAction`?

2024-08-11 14:11 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/editing/TextEditingWindow.kt
> +            }
What's the point of `UtrackCursorAction` right after `TrackCursorAction`? According to https://github.com/LatticeLadder/fcitx5-android/blob/96c40cf43a5fc86516def09c6c5183d084090be9/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/CommonKeyActionListener.kt#L170-L184 , It would call `InputConnection#getExtractedText()` on every button press, isn't it?

2024-08-13 15:39 UTC, closed without merging