Add some vibration
fcitx5-android/fcitx5-android pull request #626
Opened 2024-11-29 10:37 UTC by MOldtime

实现该issue #464

2024-11-29 10:39 UTC, rocka commented
考虑到并不是所有人都喜欢这个功能，需要加个开关，建议默认关闭

2024-11-29 11:59 UTC, MOldtime commented
已添加了开关，但是这个不太好命名，如果可以的话，希望得到更好的建议

2024-12-01 02:54 UTC, PRO-2684 commented
> 已添加了开关，但是这个不太好命名，如果可以的话，希望得到更好的建议

- Continuous Vibration
- Vibrate on Each Deletion

2024-12-01 03:09 UTC, MOldtime commented
> > 已添加了开关，但是这个不太好命名，如果可以的话，希望得到更好的建议
> 
>     * Continuous Vibration
> 
>     * Vibrate on Each Deletion
第一个看起来不错。
除了长按删除时的震动，还有滑动删除时 和 空格移动光标时的震动，不过只做了一个开关来控制
或许我应该增加设置项使其更好命名

2024-12-10 06:47 UTC, keta1 commented
> > 已添加了开关，但是这个不太好命名，如果可以的话，希望得到更好的建议
> 
> * Continuous Vibration
> * Vibrate on Each Deletion

Haptic Feedback

2024-12-10 14:17 UTC, rocka commented
我想到一个比较合适的名字： Haptic feedback on key repeat

但是直译到中文“按键重复时振动”好像不太通顺

2024-12-11 01:10 UTC, MOldtime commented
已修改默认名为：`Haptic feedback on key repeat`

2024-12-11 11:44 UTC, MOldtime commented
增加了：输入框时没有字时停止连续震动
不知道实现方式有没有问题

2024-12-16 15:27 UTC, rocka requested changes
TLDR: 不建议用 selection range 作为 haptic feedback 的判断条件，直接在 onAction 的时候判断就行了

另外长按退格键连续删除的振动反馈都有了，顺便给左划退格键选择删除也加上吧

https://github.com/fcitx5-android/fcitx5-android/blob/78cfe81769f673e9c9ec8e1e3557342106843fd4/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt#L187-L202

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/data/prefs/AppPrefs.kt
> +        val hapticFeedback = switch(R.string.haptic_feedback, "haptic_feedback", false)
属性名， R.string 和 preference key 的名字都应该改一下，需要体现这个选项的具体作用
```suggestion
        val hapticOnRepeat = switch(R.string.haptic_on_repeat, "haptic_on_repeat", false)
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt
> +        inputView?.updateSelection(0, 0)
不要手动更改 selection 的状态，它唯一的数据源应该是 InputMethodService 中 onUpdateSelection callback

```suggestion
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt
> +        prefs.keyboard.hapticFeedback,
`recreateInputViewPrefs` 应该只在“必须重新创建 InputView 才能完成对 prefs 行为的更新”的情况下使用。在这个场景里，完全可以把对 prefs 的判断移动到触发 haptic feedback 的时候。

```suggestion
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +    private val hapticFeedback by prefs.keyboard.hapticFeedback
```suggestion
    private val hapticOnRepeat by prefs.keyboard.hapticOnRepeat
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +            } else null
我建议把 haptic feedback 的动作放到下面 repeat(){} 里面

```suggestion
```

另外不建议把 cursor range 作为是否振动的依据，首先并不是所有程序都支持汇报光标位置，其次即使它不振动了，但 onAction 还是在持续地触发，也就是还在持续地发送方向键，这个行为不太复合直觉。从用户的角度看，如果振动停止了，发送方向键的这个行为应该也会停止。

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +                                    vibration?.invoke(view, selection.end >= selection.start)
```suggestion
                                    if (hapticOnRepeat) InputFeedbacks.hapticFeedback(view)
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +                                vibration?.invoke(view, selection.end > selection.start)
```suggestion
                                if (hapticOnRepeat) InputFeedbacks.hapticFeedback(view)
```

同上

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +                        } else { _ -> onAction(it.action) }
同上上

BackspaceKey 在这里应该并不特殊，不需要专门判断它，也就是说所有能 Repeat 的 Key 都应该能自动获得 "Haptic feedbac on key repeat" 的能力

另外 selection range 不是这么用的，它的数据来自 [InputMethodService#onUpdateSelection](https://developer.android.com/reference/android/inputmethodservice/InputMethodService#onUpdateSelection(int,%20int,%20int,%20int,%20int,%20int)) ，当 start=end 时，表现为光标，当 start>end 时，表现为文字的选区，所以这个条件在这里也不会有什么用处

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +
```suggestion
```

2024-12-16 15:27 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/KeyboardWindow.kt
> +
```suggestion
```

2024-12-17 00:41 UTC, MOldtime commented on app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt
> +        prefs.keyboard.hapticFeedback,
这里是因为，回调里重复判断是没有必要的，用户不会频繁的更改设置，如果把判断挪在外面，也许大概可以节约忽略不计的性能开销
我将会在稍后有空修改它们

2024-12-17 00:48 UTC, MOldtime commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +            } else null
确实不太了解光标的使用，感谢提醒，这里的函数也会在移动光标和滑动删除时使用，出于上面所说的性能考虑，就挪出 来了，就这么写了

2024-12-17 00:49 UTC, MOldtime commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +                        } else { _ -> onAction(it.action) }
考虑pr可能需要尽可能的小，所以还是做了个判断，避免特殊情况
将在后续修改

2024-12-17 03:35 UTC, MOldtime commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +
注意到 滑动选中的判断在这里，是否还是需要 cursor range 的辅助
https://github.com/fcitx5-android/fcitx5-android/blob/master/app/src/main/java/org/fcitx/fcitx5/android/input/FcitxInputMethodService.kt#L432-L441

2024-12-20 12:55 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +
在 onAction 的同时触发 haptic feedback 即可，不需要把 feedback 耦合在实际的输入法逻辑里。换句话说，就是加到这里

https://github.com/fcitx5-android/fcitx5-android/blob/e34a22fadcc360b632fb120f69c7200e2d4af691/app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt#L182-L203

2024-12-20 12:58 UTC, rocka commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +import org.fcitx.fcitx5.android.input.cursor.CursorRange
把这 import 也去掉吧，反正下面没有用到

```suggestion
```

2024-12-20 13:14 UTC, MOldtime commented on app/src/main/java/org/fcitx/fcitx5/android/input/keyboard/BaseKeyboard.kt
> +import org.fcitx.fcitx5.android.input.cursor.CursorRange
抱歉，忘记格式化了

2024-12-20 15:49 UTC, rocka approved these changes
LGTM 😎

2024-12-22 16:54 UTC, merged